equip-delay: 5 # Seconds

sword:
  material: DIAMOND_SWORD
  display-name: "&cCombat Sword"
  lore:
    - "&7Use this sword to fight"
    - "&7Get ready for combat!"
    - ""
    - "&bEnchants&7:"
    - "  &7• Sharpness III"
    - "  &7• Unbreaking I"
  enchants:
    sharpness: 3
    unbreaking: 1

armor:
  helmet:
    material: DIAMOND_HELMET
    display-name: "&bBattle Helmet"
    lore:
      - "&7Combat protection"
      - ""
      - "&bEnchants&7:"
      - "  &7• Protection II"
  chestplate:
    material: DIAMOND_CHESTPLATE
    display-name: "&bBattle Chestplate"
    lore:
      - "&7Combat protection"
      - ""
      - "&bEnchants&7:"
      - "  &7• Protection II"
    enchants:
      protection: 2
  leggings:
    material: DIAMOND_LEGGINGS
    display-name: "&bBattle Leggings"
    lore:
      - "&7Combat protection"
      - ""
      - "&bEnchants&7:"
      - "  &7• Protection II"
    enchants:
      protection: 2
  boots:
    material: DIAMOND_BOOTS
    display-name: "&bBattle Boots"
    lore:
      - "&7Combat protection"
      - ""
      - "&bEnchants&7:"
      - "  &7• Protection II"
      - "  &7• Feather Falling II"
    enchants:
      protection: 2
      feather_falling: 2