server-name: "lobby-1"
spawn-location: ""

welcome-message:
  - "&7&m----------------------------------------"
  - "&fWelcome &e%player% &fto &6&lServer Network"
  - ""
  - " &a&l┃ Store &fstore.server.net"
  - " &9&l┃ Discord &fdiscord.server.net"
  - " &b&l┃ Twitter &f@ServerNetwork"
  - "&7&m----------------------------------------"

chat-system:
  enabled: true
  format: "&7%player% &8» &7%message%"

boss-bar-system: # NOT AVAILABLE IN 1.8
  enabled: true
  types:
    example-1:
      title: "&aExample #1 | Boss Bar"
      color: GREEN
      style: SOLID
    example-2:
      title: "&cExample #2 | Boss Bar"
      color: RED
      style: SOLID
    example-3:
      title: "&bExample #3 | Boss Bar"
      color: BLUE
      style: SOLID

hub-sword-system:
  enabled: true
  delay: 5
  sword:
    slot: 4
    name: "&cCombat Sword"
    lore:
      - "&7Use this sword to fight"
      - "&7Get ready for combat"
    material: DIAMOND_SWORD
    enchants:
      damage_all: 3
  equipment:
    helmet:
      name: "&cBattle Helmet"
      material: DIAMOND_HELMET
      enchants:
        protection_environmental: 2
    chestplate:
      name: "&cBattle Chestplate"
      material: DIAMOND_CHESTPLATE
      enchants:
        protection_environmental: 2
    leggings:
      name: "&cBattle Leggings"
      material: DIAMOND_LEGGINGS
      enchants:
        protection_environmental: 2
    boots:
      name: "&cBattle Boots"
      material: DIAMOND_BOOTS
      enchants:
        protection_environmental: 2