server-name: "lobby-1"
spawn-location: ""

welcome-message:
  - "&7&m----------------------------------------"
  - "&fWelcome &e%player% &fto &6&lServer Network"
  - ""
  - " &a&l┃ Store &fstore.server.net"
  - " &9&l┃ Discord &fdiscord.server.net"
  - " &b&l┃ Twitter &f@ServerNetwork"
  - "&7&m----------------------------------------"

chat-system:
  enabled: true
  format: "&7%player% &8» &7%message%"